// Copyright 2016 The G3N Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package app implements a cross-platform G3N app.
package app

import (
	"fmt"
	"github.com/derekmu/g3n/audio/al"
	"github.com/derekmu/g3n/renderer"
	"github.com/derekmu/g3n/window"
	"log"
	"time"
)

var singleton *Application

// OnExit is the event generated by Application when the user
// tries to close the window (desktop) or the Exit() method is called.
const OnExit = "app.OnExit"

// Application is the central, singleton object for G3N.
type Application struct {
	window.IWindow                    // Embedded GlfwWindow
	keyState       *window.KeyState   // Keep track of keyboard state
	renderer       *renderer.Renderer // Renderer object
	audioDev       *al.Device         // Default audio device
	startTime      time.Time          // Application start time
	frameStart     time.Time          // Frame start time
	frameDelta     time.Duration      // Duration of last frame
}

// GetApplication returns the Application singleton. It creates the singleton the first time it is called.
func GetApplication(width, height int, title string) *Application {
	if singleton != nil {
		return singleton
	}
	singleton = new(Application)
	err := window.Init(width, height, title)
	if err != nil {
		panic(err)
	}
	singleton.IWindow = window.Get()
	singleton.keyState = window.NewKeyState(singleton)
	singleton.renderer = renderer.NewRenderer(singleton.Gls())
	err = singleton.renderer.AddDefaultShaders()
	if err != nil {
		panic(fmt.Errorf("AddDefaultShaders:%v", err))
	}
	return singleton
}

// Run starts the update loop and calls the user-provided update function every frame.
func (a *Application) Run(update func(rend *renderer.Renderer, deltaTime time.Duration)) {
	a.startTime = time.Now()
	a.frameStart = time.Now()
	for {
		if a.IWindow.(*window.GlfwWindow).ShouldClose() {
			a.Dispatch(OnExit, nil)
			break
		}
		now := time.Now()
		a.frameDelta = now.Sub(a.frameStart)
		a.frameStart = now
		update(a.renderer, a.frameDelta)
		a.IWindow.(*window.GlfwWindow).SwapBuffers()
		a.IWindow.(*window.GlfwWindow).PollEvents()
	}
	if a.audioDev != nil {
		err := al.CloseDevice(a.audioDev)
		if err != nil {
			log.Print("failed to close audio device", err)
		}
	}
	a.Destroy()
}

// Exit requests to terminate the application.
func (a *Application) Exit() {
	a.IWindow.(*window.GlfwWindow).SetShouldClose(true)
}

// Renderer returns the application's renderer.
func (a *Application) Renderer() *renderer.Renderer {
	return a.renderer
}

// KeyState returns the application's KeyState.
func (a *Application) KeyState() *window.KeyState {
	return a.keyState
}

// RunTime returns the elapsed duration since the call to Run().
func (a *Application) RunTime() time.Duration {
	return time.Since(a.startTime)
}

// OpenDefaultAudioDevice opens the default audio device setting it to the current context.
func (a *Application) OpenDefaultAudioDevice() error {
	// Opens default audio device
	var err error
	a.audioDev, err = al.OpenDevice("")
	if err != nil {
		return fmt.Errorf("opening OpenAL default device: %s", err)
	}
	// Check for OpenAL effects extension support
	var attribs []int
	if al.IsExtensionPresent("ALC_EXT_EFX") {
		attribs = []int{al.MAX_AUXILIARY_SENDS, 4}
	}
	// Create audio context
	acx, err := al.CreateContext(a.audioDev, attribs)
	if err != nil {
		return fmt.Errorf("creating OpenAL context: %s", err)
	}
	// Makes the context the current one
	err = al.MakeContextCurrent(acx)
	if err != nil {
		return fmt.Errorf("setting OpenAL context current: %s", err)
	}
	return nil
}
